export const APP_NAME = 'Cooky';

export const AUTH_STACK = 'AUTH_STACK';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN';

export const APP_NAVIGATOR = 'APP_NAVIGATOR';
export const TAB_NAVIGATOR = 'TAB_NAVIGATOR';
export const FOOD_STACK = 'FOOD_STACK';
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const FOOD_LIST_SCREEN = 'FOOD_LIST_SCREEN';
export const ADD_FOOD_SCREEN = 'ADD_FOOD_SCREEN';
export const SCAN_FOOD_SCREEN = 'SCAN_FOOD_SCREEN';
export const RECIPE_STACK = 'RECIPE_STACK';
export const RECIPE_LIST_SCREEN = 'RECIPE_LIST_SCREEN';
export const RECIPE_SCREEN = 'RECIPE_SCREEN';
export const ADD_RECIPE_SCREEN = 'ADD_RECIPE_SCREEN';
export const COOKING_STACK = 'COOKING_STACK';
export const COOKING_LIST_SCREEN = 'COOKING_LIST_SCREEN';
export const COOKING_SCREEN = 'COOKING_SCREEN';
